// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20250528143741_CorridoTipoUnidadeGestora")]
    partial class CorridoTipoUnidadeGestora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AgendaConsulta")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ProcessoAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConclusaoExterna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusaoInterna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrevisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPrioridade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoPrioridade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prioridade")
                        .HasColumnType("bit");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeGestoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProcessosAgenda", "AgendaConsulta");
                });
#pragma warning restore 612, 618
        }
    }
}
